### ISSUE TITLE
Doc Suggestion

### ISSUE THREAD

**Issue by JakeAndrew** [vovanmix/atom-move-tab-or-split#2]
Hi. Thank you for your package. It's the only one I found that I was able to get to work.
It'd be nice to have a couple brief blurbs added to the ReadMe:

* You must first click body text for the shortcut keys to work. (Simply clicking the tab at top or hoping it will remember where you were last will not work.)
* "Special" tabs like Settings or a Markdown preview cannot be moved with this pluggin.

**Comment by vovanmix** [comment]
Thank you for the suggestion! I updated the readme!

**Comment by JakeAndrew** [comment]
Thank you. I'm updating some doc at [Snowdrift.coop](https://git.snowdrift.coop/sd/snowdrift) that will soon reference this project, if they accept my merge request. So this will probably help my readers, too.
